import swaggerUi from "swagger-ui-express";
import swaggerJsdoc from "swagger-jsdoc";
import listEndpoints from "express-list-endpoints";

/**
 * Base Swagger (OpenAPI 3) configuration.
 * This defines general API metadata and tells swagger-jsdoc
 * where to scan for @swagger annotations.
 */
const swaggerOptions = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: process.env.APP_NAME ?? "Backend-Mid-Specialism",
      version: process.env.APP_VERSION ?? "0.0.1",
      description:
        "REST API for an events booking platform. " +
        "The public catalog endpoints allow browsing events without authentication. ",
    },
    tags: [
      {
        name: "Events",
        description:
          "Full event management (includes optional admin operations).",
      },
    ],
    components: {
      schemas: {
        Event: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            title: { type: "string", example: "Live Jazz Trio" },
            description: {
              type: "string",
              example: "An intimate jazz evening.",
            },
            price: { type: "number", example: 150 },
            currency: { type: "string", example: "DKK" },
            created_at: {
              type: "string",
              format: "date-time",
              example: "2026-01-15T19:00:00.000Z",
            },
            updated_at: {
              type: "string",
              format: "date-time",
              example: "2026-01-15T19:00:00.000Z",
            },
          },
        },
        PaginatedEvents: {
          type: "object",
          properties: {
            data: {
              type: "array",
              items: { $ref: "#/components/schemas/Event" },
            },
            meta: {
              type: "object",
              properties: {
                page: { type: "integer", example: 0 },
                pageSize: { type: "integer", example: 20 },
                totalItems: { type: "integer", example: 42 },
                totalPages: { type: "integer", example: 9 },
              },
            },
          },
        },
        Error: {
          type: "object",
          properties: {
            error: {
              type: "object",
              properties: {
                status: { type: "integer", example: 404 },
                message: { type: "string", example: "Route not found" },
              },
            },
          },
        },
      },
    },
  },
  apis: ["./src/routers/**/*.js", "./src/routers/*.js"],
};

/**
 * Default OpenAPI operation stub.
 *
 * Used when an endpoint has NO @swagger documentation.
 * Ensures that every route still appears in Swagger UI.
 */
const openApiEndpointSpecStub = {
  tags: ["Undocumented"],
  responses: {
    200: { description: "OK" },
  },
};

const swaggerSpec = swaggerJsdoc(swaggerOptions);
const swaggerServe = swaggerUi.serve;
const supportedHttpMethods = new Set([
  "get",
  "post",
  "put",
  "patch",
  "delete",
  "options",
  "head",
]);

/**
 * Convert Express route params to OpenAPI path params.
 *
 * Examples:
 * - /api/events/:id -> /api/events/{id}
 * - /api/users/:userId/orders/:orderId -> /api/users/{userId}/orders/{orderId}
 *
 * @param {string} path
 * @returns {string}
 */
function expressPathToOpenApiPath(path) {
  return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

/**
 * Generates OpenAPI "paths" object automatically
 * by inspecting the Express app router stack.
 *
 * Undocumented routes are converted into OpenAPI-compatible
 * path syntax so they can merge correctly with manually
 * documented @swagger definitions.
 *
 * @param {import("express").Application} app
 * @returns {object}
 *
 * Example output:
 * {
 *   "/api/users": {
 *     get: { ... },
 *     post: { ... }
 *   }
 * }
 */
const generateOpenApiSpecs = (app) => {
  const specs = {};

  for (const ep of listEndpoints(app)) {
    // Skip non-API utility routes (e.g. /, /docs) from undocumented stubs.
    if (!ep.path.startsWith("/api")) {
      continue;
    }

    const normalizedPath = expressPathToOpenApiPath(ep.path);

    specs[normalizedPath] ??= {};

    for (const method of ep.methods) {
      const m = method.toLowerCase();

      if (!supportedHttpMethods.has(m)) {
        continue;
      }

      specs[normalizedPath][m] ??= {
        ...openApiEndpointSpecStub,
        summary: `Undocumented: ${method} ${normalizedPath}`,
      };
    }
  }

  return specs;
};

/**
 * Initializes Swagger UI with merged specification.
 *
 * Steps:
 *  1. Auto-generate path specs from Express routes
 *  2. Merge with swagger-jsdoc output
 *     (Manual @swagger docs override auto stubs)
 *  3. Mount Swagger UI at /docs
 *
 * @param {import("express").Application} app - Express application instance
 */
const swaggerSetup = (app) => {
  const autoGeneratedSpecs = generateOpenApiSpecs(app);

  // Start from the jsdoc spec (source of truth)
  const mergedSpec = { ...swaggerSpec };
  mergedSpec.paths ??= {};

  // Only add stubs where docs are missing
  for (const [path, ops] of Object.entries(autoGeneratedSpecs)) {
    mergedSpec.paths[path] ??= {};

    for (const [method, opSpec] of Object.entries(ops)) {
      mergedSpec.paths[path][method] ??= opSpec;
    }
  }

  app.use("/docs", swaggerServe, swaggerUi.setup(mergedSpec));
};

export default swaggerSetup;
